Exercise 2
daoduong-saritasa/learn-docker pull request #2
Opened 2023-01-16 05:28 UTC by daoduong-saritasa

2023-01-24 04:52 UTC, pavelzadorin-saritasa requested changes
Your API falls with an error on incorrect user data.

And by architecture, you are using a direct database access from the endpoint controller, those. in other words, you work with repository directly from view, this is bad-practice: https://www.oreilly.com/library/view/software-architecture-patterns/9781491971437/ch01.html. Please look again at the approach with active record pattern.

2023-02-03 12:20 UTC, pavelzadorin-saritasa approved these changes

2023-02-03 12:20 UTC, pavelzadorin-saritasa commented on ex2/api/models/user.js
> +  #email;
I've never seen this syntax using, this is it: http://devdoc.net/web/developer.mozilla.org/en-US/docs/JavaScript/Sharp_variables_in_JavaScript.html? but then this feature is obsolete and not recomended to use.
But you can use actual class field feature: https://javascript.info/class#class-fields

2023-02-03 12:20 UTC, pavelzadorin-saritasa commented on ex2/api/models/user.js
> +    return result.rows[0];
I think just returning a result from the database is not safe, with changes to the structure on the database side, your application will receive incorrect data and strange errors.
I am sure that the approach using model mappers (as we do in front-end solutions when processing data from the API) would be perfect in this case too.

2023-02-06 03:02 UTC, daoduong-saritasa commented on ex2/api/models/user.js
> +  #email;
This syntax is [private declaration](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) in javascript class

2023-02-06 10:26 UTC, pavelzadorin-saritasa commented on ex2/api/models/user.js
> +  #email;
Ou, ok, the feature was included in the standard only last year), but it seems that all browsers already support it.

2023-02-06 10:56 UTC, merged